I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla M40 24GB
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:82:00.0
Total memory: 22.43GiB
Free memory: 22.32GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:82:00.0)
  0%|          | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ruppaal/696DS/bi-att-flow/basic/cli.py", line 109, in <module>
    tf.app.run()
  File "/home/ruppaal/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/ruppaal/696DS/bi-att-flow/basic/cli.py", line 106, in main
    m(config)
  File "/home/ruppaal/696DS/bi-att-flow/basic/main.py", line 23, in main
    _train(config)
  File "/home/ruppaal/696DS/bi-att-flow/basic/main.py", line 99, in _train
    loss, summary, train_op = trainer.step(sess, batches, get_summary=get_summary)
  File "/home/ruppaal/696DS/bi-att-flow/basic/trainer.py", line 65, in step
    feed_dict.update(model.get_feed_dict(ds, True))
  File "/home/ruppaal/696DS/bi-att-flow/basic/model.py", line 304, in get_feed_dict
    start_idx, stop_idx = random.choice(yi)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla M40 24GB
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:82:00.0
Total memory: 22.43GiB
Free memory: 22.32GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:82:00.0)
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ruppaal/696DS/bi-att-flow/basic/cli.py", line 109, in <module>
    tf.app.run()
  File "/home/ruppaal/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/ruppaal/696DS/bi-att-flow/basic/cli.py", line 106, in main
    m(config)
  File "/home/ruppaal/696DS/bi-att-flow/basic/main.py", line 25, in main
    _test(config)
  File "/home/ruppaal/696DS/bi-att-flow/basic/main.py", line 150, in _test
    graph_handler.initialize(sess)
  File "/home/ruppaal/696DS/bi-att-flow/basic/graph_handler.py", line 25, in initialize
    self._load(sess)
  File "/home/ruppaal/696DS/bi-att-flow/basic/graph_handler.py", line 51, in _load
    assert checkpoint is not None, "cannot load checkpoint at {}".format(save_dir)
AssertionError: cannot load checkpoint at out/newsqatest/basic/00/save
